Rettelser og endringsforslag til schematron
Informasjonsforvaltning/tbx-ap-no pull request #18
Opened 2021-09-08 08:59 UTC by OyvindLGjesdal

Min kollega @tonem har bruk schematron og relax-ng skjemaet fra eksemplene for å jobbe med mapping mellom skosno og tbx-ap-no og har kommet med noen rettelser og endringsforslag.

* hoved-namespace har endret seg i schema for RelaxNG og såvidt vi kan se fra eksempler er dette også gjort i eksempler på tbx sine infosider. Vi har ikke tilgang til ISO-dokumentet, så kan ikke dobbeltsjekke fasit, men gitt at eksempler og relax-ng fil som vises til i dokumentasjon har byttet, har vi kommet frem til at det trolig er en endring på namespace fra `urn:iso:std:iso:30042:ed:3.0` til `urn:iso:std:iso:30042:ed:2` (selv om tall går bakover)
* Det er litt skrivefeil i xpath utrykk (ugyldig xpath) som er rettet
* Vi foreslår å endre navn  på dialect til TBX-AP-NO fra TBX-AP-No

Ellers takk for publiseringen av schemaet, det kom godt med for å jobbe med mapping til tbx-ap-no og forventninger til utvekslingsformatet.

2021-09-13 08:15 UTC, jimjyang requested changes

2021-09-13 08:15 UTC, jimjyang commented on schematron/TBX-AP-No_DCA.sch
> +  <ns uri="urn:iso:std:iso:30042:ed:2" prefix="tbx"/>
Det står "The TBX-Core namespace is: urn:iso:std:iso:30042:ed-2" i standarden.

2021-09-13 08:15 UTC, jimjyang commented on schematron/TBX-AP-No_DCA.sch
>        <assert test="false()">DCT style elements are not permitted in DCA style TBX.</assert>
her også.

2021-09-13 08:18 UTC, jimjyang commented
Takk for gode kommentarer og rettinger!

2021-09-14 12:09 UTC, OyvindLGjesdal commented on schematron/TBX-AP-No_DCA.sch
>        <assert test="false()">DCT style elements are not permitted in DCA style TBX.</assert>
Det ser rett ut ja,  Vi tok ned en versjon av relaxng skjemaet også, så har klart å korrigere/rette begge steder.

2021-09-15 07:09 UTC, jimjyang approved these changes

2021-12-10 14:49 UTC, merged